### ISSUE TITLE
A suggestion about loading data

### ISSUE THREAD

**Issue by tritium21** [justinwp/croplands#1]
It has recently come to my attention in discussions with the maintainer of another python package developer, that this project contains a 13k+ long dict literal, and that this is the cause of a few bugs (namely with coverage testing).

I would suggest not using a massive literal, and instead packing the data in a binary, and using MMAP to randomly access it.  Creating a huge tree of objects cannot be memory or processor efficient.

**Comment by justinwp** [comment]
Should do point in polygon work in Google Earth Engine with a celery task instead.
